/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyInsertionSort */

#ifndef _Included_MyInsertionSort
#define _Included_MyInsertionSort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyInsertionSort
 * Method:    insertionSort
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_MyInsertionSort_insertionSort
  (JNIEnv *, jobject, jintArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
